# Generated by Django 3.2.3 on 2021-05-29 12:45

import buildings.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_rename_post_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDraft',
            fields=[
                ('general_id', models.AutoField(primary_key=True, serialize=False, verbose_name='general id')),
                ('risk_category', models.CharField(choices=[('NA', 'N/A'), ('U1', 'U1'), ('U2', 'U2'), ('U3', 'U3'), ('U4', 'U4'), ('RS1', 'RS I'), ('RS2', 'RS II'), ('RS3', 'RS III'), ('RS4', 'RS IV')], db_index=True, default=buildings.models.SeismicCategoryChoice['NA'], max_length=3, verbose_name='risk category')),
                ('registration_number', models.IntegerField(null=True, verbose_name='registration number')),
                ('examination_year', models.IntegerField(null=True, verbose_name='examination year')),
                ('certified_expert', models.CharField(max_length=100, null=True, verbose_name='certified expert')),
                ('observations', models.CharField(max_length=1000, null=True, verbose_name='observations')),
                ('lat', models.FloatField(null=True, verbose_name='latitude')),
                ('lng', models.FloatField(null=True, verbose_name='longitude')),
                ('county', models.CharField(max_length=60, verbose_name='county')),
                ('address', models.CharField(max_length=250, null=True, verbose_name='address')),
                ('street_number', models.CharField(max_length=100, verbose_name='street number')),
                ('locality', models.CharField(max_length=20, verbose_name='locality')),
                ('year_built', models.IntegerField(null=True, verbose_name='year built')),
                ('height_regime', models.CharField(max_length=50, null=True, verbose_name='height regime')),
                ('apartment_count', models.IntegerField(null=True, verbose_name='apartment count')),
                ('surface', models.FloatField(null=True, verbose_name='surface')),
                ('cadastre_number', models.IntegerField(null=True, verbose_name='cadastre number')),
                ('land_registry_number', models.CharField(max_length=50, null=True, verbose_name='land registry number')),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (-1, 'Rejected')], db_index=True, default=0, verbose_name='status')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='created on')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
            ],
            options={
                'verbose_name': 'building draft',
                'verbose_name_plural': 'building drafts',
            },
            managers=[
                ('for_new_buildings', django.db.models.manager.Manager()),
            ],
        ),
    ]
